export const PRESS_C_BUTTON = 'PRESS_C_BUTTON';
export const PRESS_BACKSPACE_BUTTON = 'PRESS_BACKSPACE_BUTTON';
export const PRESS_NUMBER_BUTTON = 'PRESS_NUMBER_BUTTON';
export const PRESS_OPERATION_BUTTON = 'PRESS_OPERATION_BUTTON';
export const PRESS_EQUALS_TO_BUTTON = 'PRESS_EQUALS_TO_BUTTON';
export const PRESS_TOGGLE_SIGN_BUTTON = 'PRESS_TOGGLE_SIGN_BUTTON';
export const PRESS_DOT_BUTTON = 'PRESS_DOT_BUTTON';


export const PRESS_CURRENCY_NUMBER_BUTTON = 'PRESS_CURRENCY_NUMBER_BUTTON';
export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY';
export const CHANGE_TARGET_CURRENCY = 'CHANGE_TARGET_CURRENCY';
export const PRESS_CURRENCY_BACKSPACE_BUTTON = 'PRESS_CURRENCY_BACKSPACE_BUTTON';
export const PRESS_CURRENCY_CLEAR_BUTTON = 'PRESS_CURRENCY_CLEAR_BUTTON';
export const PRESS_CURRENCY_DOT_BUTTON = 'PRESS_CURRENCY_DOT_BUTTON';
export const STORE_RATES_IN_STATE = 'STORE_RATES_IN_STATE';
