export const PRESS_C_BUTTON = 'PRESS_C_BUTTON';
export const PRESS_BACKSPACE_BUTTON = 'PRESS_BACKSPACE_BUTTON';
export const PRESS_NUMBER_BUTTON = 'PRESS_NUMBER_BUTTON';
export const PRESS_OPERATION_BUTTON = 'PRESS_OPERATION_BUTTON';
export const PRESS_EQUALS_TO_BUTTON = 'PRESS_EQUALS_TO_BUTTON';